-- Script d'initialisation complet pour la table radiology_exam_type
INSERT INTO radiology_exam_type (name, category, description, notes, created_at, updated_at)
VALUES
  ('Radiographie pulmonaire', 'Radiographie', 'Examen standard des poumons', 'A jeun non nécessaire', NOW(), NOW()),
  ('Radiographie du rachis cervical', 'Radiographie', 'Examen de la colonne cervicale', 'Retirer les bijoux', NOW(), NOW()),
  ('Radiographie du rachis dorsal', 'Radiographie', 'Examen de la colonne dorsale', NULL, NOW(), NOW()),
  ('Radiographie du rachis lombaire', 'Radiographie', 'Examen de la colonne lombaire', NULL, NOW(), NOW()),
  ('Radiographie du bassin', 'Radiographie', 'Examen du bassin osseux', NULL, NOW(), NOW()),
  ('Radiographie des sinus', 'Radiographie', 'Examen des sinus de la face', NULL, NOW(), NOW()),
  ('Radiographie du crâne', 'Radiographie', 'Examen du crâne', NULL, NOW(), NOW()),
  ('Radiographie abdominale', 'Radiographie', 'Examen de l''abdomen sans préparation', 'A jeun recommandé', NOW(), NOW()),
  ('Radiographie des membres supérieurs', 'Radiographie', 'Examen des bras, épaules, mains', NULL, NOW(), NOW()),
  ('Radiographie des membres inférieurs', 'Radiographie', 'Examen des jambes, genoux, pieds', NULL, NOW(), NOW()),
  
  ('Échographie abdominale', 'Échographie', 'Examen des organes abdominaux', 'A jeun depuis 6h', NOW(), NOW()),
  ('Échographie pelvienne', 'Échographie', 'Examen des organes pelviens', 'Vessie pleine', NOW(), NOW()),
  ('Échographie thyroïdienne', 'Échographie', 'Examen de la thyroïde', NULL, NOW(), NOW()),
  ('Échographie mammaire', 'Échographie', 'Examen des seins', NULL, NOW(), NOW()),
  ('Échographie doppler veineux', 'Échographie', 'Examen des veines', NULL, NOW(), NOW()),
  ('Échographie doppler artériel', 'Échographie', 'Examen des artères', NULL, NOW(), NOW()),
  ('Échographie cardiaque', 'Échographie', 'Examen du cœur', NULL, NOW(), NOW()),
  ('Échographie obstétricale', 'Échographie', 'Suivi de grossesse', 'Vessie modérément pleine', NOW(), NOW()),
  ('Échographie prostatique', 'Échographie', 'Examen de la prostate', 'Vessie pleine', NOW(), NOW()),
  ('Échographie testiculaire', 'Échographie', 'Examen des testicules', NULL, NOW(), NOW()),
  
  ('Scanner cérébral', 'Scanner', 'Examen du cerveau sans injection', NULL, NOW(), NOW()),
  ('Scanner thoracique', 'Scanner', 'Examen du thorax', 'Allergie aux produits iodés à signaler', NOW(), NOW()),
  ('Scanner abdominal', 'Scanner', 'Examen de l''abdomen', 'Préparation intestinale', NOW(), NOW()),
  ('Scanner pelvien', 'Scanner', 'Examen du pelvis', NULL, NOW(), NOW()),
  ('Scanner rachidien', 'Scanner', 'Examen de la colonne vertébrale', NULL, NOW(), NOW()),
  ('Scanner ORL', 'Scanner', 'Examen des sinus et sphère ORL', NULL, NOW(), NOW()),
  ('Scanner angio-TDM', 'Scanner', 'Examen vasculaire avec injection', 'Contre-indication insuffisance rénale', NOW(), NOW()),
  ('Scanner des membres', 'Scanner', 'Examen des bras ou jambes', NULL, NOW(), NOW()),
  ('Scanner facial', 'Scanner', 'Examen des os de la face', NULL, NOW(), NOW()),
  ('Scanner corps entier', 'Scanner', 'Examen complet', 'Réservé à certains protocoles', NOW(), NOW()),
  
  ('IRM cérébrale', 'IRM', 'Imagerie du cerveau', 'Contre-indication pacemaker', NOW(), NOW()),
  ('IRM rachidienne', 'IRM', 'Imagerie de la colonne vertébrale', NULL, NOW(), NOW()),
  ('IRM articulaire', 'IRM', 'Examen des articulations', 'Immobilité requise', NOW(), NOW()),
  ('IRM abdominale', 'IRM', 'Imagerie de l''abdomen', NULL, NOW(), NOW()),
  ('IRM pelvienne', 'IRM', 'Imagerie du pelvis', NULL, NOW(), NOW()),
  ('IRM cardiaque', 'IRM', 'Examen du cœur', 'Coordination respiratoire', NOW(), NOW()),
  ('IRM mammaire', 'IRM', 'Examen des seins', NULL, NOW(), NOW()),
  ('IRM prostatique', 'IRM', 'Examen de la prostate', NULL, NOW(), NOW()),
  ('IRM spectroscopie', 'IRM', 'Technique spécialisée', NULL, NOW(), NOW()),
  ('IRM diffusion', 'IRM', 'Technique spécialisée', NULL, NOW(), NOW()),
  
  ('Mammographie', 'Radiographie', 'Examen des seins', '1ère partie de cycle', NOW(), NOW()),
  ('Ostéodensitométrie', 'Autre', 'Mesure de la densité osseuse', NULL, NOW(), NOW()),
  ('Arthroscanner', 'Scanner', 'Examen articulaire avec contraste', NULL, NOW(), NOW()),
  ('Uroscanner', 'Scanner', 'Examen des voies urinaires', NULL, NOW(), NOW()),
  ('Coloscanner', 'Scanner', 'Examen du côlon', 'Préparation colique rigoureuse', NOW(), NOW()),
  ('Pancréato-IRM', 'IRM', 'Examen du pancréas', NULL, NOW(), NOW()),
  ('Cholangio-IRM', 'IRM', 'Examen des voies biliaires', NULL, NOW(), NOW()),
  ('Myélographie', 'Radiographie', 'Examen de la moelle épinière', 'Hospitalisation nécessaire', NOW(), NOW()),
  ('Sialographie', 'Radiographie', 'Examen des glandes salivaires', NULL, NOW(), NOW()),
  ('Dacryoscintigraphie', 'Médecine nucléaire', 'Examen des voies lacrymales', NULL, NOW(), NOW());
