-- Script complet d'insertion pour les types de tests médicaux
INSERT INTO lab_test_type (name, category, default_unit, default_reference_range, created_at, updated_at)
VALUES
    -- 1. Hématologie
    ('Numération globulaire complète (NFS)', 'Hématologie', NULL, NULL, NOW(), NOW()),
    ('Hémoglobine (Hb)', 'Hématologie', 'g/dL', '13.5-17.5 (H), 12.0-15.5 (F)', NOW(), NOW()),
    ('Hématocrite (Ht)', 'Hématologie', '%', '40-52 (H), 36-48 (F)', NOW(), NOW()),
    ('Plaquettes', 'Hématologie', '10^3/μL', '150-450', NOW(), NOW()),
    ('Leucocytes (GB)', 'Hématologie', '10^3/μL', '4.5-11.0', NOW(), NOW()),
    ('Neutrophiles', 'Hématologie', '%', '40-75', NOW(), NOW()),
    ('Lymphocytes', 'Hématologie', '%', '20-50', NOW(), NOW()),
    ('Monocytes', 'Hématologie', '%', '2-10', NOW(), NOW()),
    ('Éosinophiles', 'Hématologie', '%', '0-6', NOW(), NOW()),
    ('Basophiles', 'Hématologie', '%', '0-2', NOW(), NOW()),
    ('VS (Vitesse de Sédimentation)', 'Hématologie', 'mm/h', '<15 (H), <20 (F)', NOW(), NOW()),
    ('Frottis sanguin', 'Hématologie', NULL, NULL, NOW(), NOW()),
    ('Réticulocytes', 'Hématologie', '%', '0.5-1.5', NOW(), NOW()),
    
    -- 2. Biochimie
    ('Glycémie à jeun', 'Biochimie', 'mg/dL', '70-99', NOW(), NOW()),
    ('Glycémie post-prandiale', 'Biochimie', 'mg/dL', '<140', NOW(), NOW()),
    ('HbA1c', 'Biochimie', '%', '4.0-6.0', NOW(), NOW()),
    ('Créatinine', 'Biochimie', 'mg/dL', '0.7-1.3 (H), 0.6-1.1 (F)', NOW(), NOW()),
    ('Urée', 'Biochimie', 'mg/dL', '10-50', NOW(), NOW()),
    ('Acide urique', 'Biochimie', 'mg/dL', '3.4-7.0 (H), 2.4-6.0 (F)', NOW(), NOW()),
    ('Bilirubine totale', 'Biochimie', 'mg/dL', '0.2-1.2', NOW(), NOW()),
    ('Bilirubine directe', 'Biochimie', 'mg/dL', '0.0-0.3', NOW(), NOW()),
    ('Bilirubine indirecte', 'Biochimie', 'mg/dL', '0.2-0.8', NOW(), NOW()),
    ('Transaminases (ASAT)', 'Biochimie', 'UI/L', '<40', NOW(), NOW()),
    ('Transaminases (ALAT)', 'Biochimie', 'UI/L', '<41 (H), <31 (F)', NOW(), NOW()),
    ('Gamma-GT', 'Biochimie', 'UI/L', '8-61 (H), 5-36 (F)', NOW(), NOW()),
    ('Phosphatases alcalines', 'Biochimie', 'UI/L', '40-130 (Adulte)', NOW(), NOW()),
    ('Amylase', 'Biochimie', 'UI/L', '30-110', NOW(), NOW()),
    ('Lipase', 'Biochimie', 'UI/L', '13-60', NOW(), NOW()),
    ('LDH', 'Biochimie', 'UI/L', '140-280', NOW(), NOW()),
    ('CPK', 'Biochimie', 'UI/L', '38-174 (H), 26-140 (F)', NOW(), NOW()),
    ('Troponine', 'Biochimie', 'ng/mL', '<0.04', NOW(), NOW()),
    ('Sodium (Na)', 'Biochimie', 'mEq/L', '135-145', NOW(), NOW()),
    ('Potassium (K)', 'Biochimie', 'mEq/L', '3.5-5.0', NOW(), NOW()),
    ('Chlore (Cl)', 'Biochimie', 'mEq/L', '98-106', NOW(), NOW()),
    ('Calcium (Ca)', 'Biochimie', 'mg/dL', '8.5-10.2', NOW(), NOW()),
    ('Phosphore (P)', 'Biochimie', 'mg/dL', '2.5-4.5', NOW(), NOW()),
    ('Magnésium (Mg)', 'Biochimie', 'mg/dL', '1.7-2.2', NOW(), NOW()),
    ('Fer sérique', 'Biochimie', 'μg/dL', '50-170 (H), 40-160 (F)', NOW(), NOW()),
    ('Ferritine', 'Biochimie', 'ng/mL', '20-300 (H), 20-200 (F)', NOW(), NOW()),
    ('Transferrine', 'Biochimie', 'mg/dL', '200-360', NOW(), NOW()),
    ('Capacité totale de fixation du fer (CTFH)', 'Biochimie', 'μg/dL', '250-450', NOW(), NOW()),
    ('Coefficient de saturation de la transferrine', 'Biochimie', '%', '20-50', NOW(), NOW()),
    ('Protéines totales', 'Biochimie', 'g/dL', '6.0-8.3', NOW(), NOW()),
    ('Albumine', 'Biochimie', 'g/dL', '3.5-5.0', NOW(), NOW()),
    ('Globulines', 'Biochimie', 'g/dL', '2.0-3.5', NOW(), NOW()),
    ('Rapport A/G', 'Biochimie', NULL, '1.0-2.2', NOW(), NOW()),
    ('Cholestérol total', 'Biochimie', 'mg/dL', '<200', NOW(), NOW()),
    ('HDL cholestérol', 'Biochimie', 'mg/dL', '>40 (H), >50 (F)', NOW(), NOW()),
    ('LDL cholestérol', 'Biochimie', 'mg/dL', '<130', NOW(), NOW()),
    ('Triglycérides', 'Biochimie', 'mg/dL', '<150', NOW(), NOW()),
    ('CRP (Protéine C Réactive)', 'Biochimie', 'mg/L', '<10', NOW(), NOW()),
    ('CRP ultrasensible', 'Biochimie', 'mg/L', '<3', NOW(), NOW()),
    
    -- 3. Hormones
    ('TSH', 'Hormones', 'μIU/mL', '0.4-4.0', NOW(), NOW()),
    ('T4 libre', 'Hormones', 'ng/dL', '0.8-1.8', NOW(), NOW()),
    ('T3 libre', 'Hormones', 'pg/mL', '2.3-4.2', NOW(), NOW()),
    ('Testostérone totale', 'Hormones', 'ng/dL', '300-1000 (H), 15-70 (F)', NOW(), NOW()),
    ('Testostérone libre', 'Hormones', 'pg/mL', '50-210 (H)', NOW(), NOW()),
    ('Estradiol', 'Hormones', 'pg/mL', '10-50 (H), Varie selon cycle (F)', NOW(), NOW()),
    ('Progestérone', 'Hormones', 'ng/mL', 'Varie selon cycle', NOW(), NOW()),
    ('FSH', 'Hormones', 'mUI/mL', '1.5-12.4 (H), Varie selon cycle (F)', NOW(), NOW()),
    ('LH', 'Hormones', 'mUI/mL', '1.7-8.6 (H), Varie selon cycle (F)', NOW(), NOW()),
    ('Prolactine', 'Hormones', 'ng/mL', '2-18 (H), 2-25 (F)', NOW(), NOW()),
    ('Cortisol (8h)', 'Hormones', 'μg/dL', '5-25', NOW(), NOW()),
    ('ACTH', 'Hormones', 'pg/mL', '7.2-63', NOW(), NOW()),
    ('GH (Hormone de croissance)', 'Hormones', 'ng/mL', '<5', NOW(), NOW()),
    ('IGF-1', 'Hormones', 'ng/mL', 'Varie selon âge', NOW(), NOW()),
    ('Parathormone (PTH)', 'Hormones', 'pg/mL', '15-65', NOW(), NOW()),
    ('Calcitonine', 'Hormones', 'pg/mL', '<8.5 (H), <5.1 (F)', NOW(), NOW()),
    ('Aldostérone', 'Hormones', 'ng/dL', '2-9 (debout), 1-5 (couché)', NOW(), NOW()),
    ('Rénine', 'Hormones', 'ng/mL/h', '0.5-4.0 (debout)', NOW(), NOW()),
    ('DHEA-S', 'Hormones', 'μg/dL', 'Varie selon âge et sexe', NOW(), NOW()),
    ('Androstènedione', 'Hormones', 'ng/dL', 'Varie selon sexe', NOW(), NOW()),
    
    -- 4. Marqueurs tumoraux
    ('PSA total', 'Marqueurs tumoraux', 'ng/mL', '<4.0', NOW(), NOW()),
    ('PSA libre', 'Marqueurs tumoraux', 'ng/mL', NULL, NOW(), NOW()),
    ('Rapport PSA libre/total', 'Marqueurs tumoraux', '%', '>25', NOW(), NOW()),
    ('CA 125', 'Marqueurs tumoraux', 'U/mL', '<35', NOW(), NOW()),
    ('CA 15-3', 'Marqueurs tumoraux', 'U/mL', '<31', NOW(), NOW()),
    ('CA 19-9', 'Marqueurs tumoraux', 'U/mL', '<37', NOW(), NOW()),
    ('ACE (Antigène Carcino-Embryonnaire)', 'Marqueurs tumoraux', 'ng/mL', '<5 (non-fumeur), <10 (fumeur)', NOW(), NOW()),
    ('AFP (Alpha-FoetoProtéine)', 'Marqueurs tumoraux', 'ng/mL', '<10', NOW(), NOW()),
    ('HCG (Bêta-HCG)', 'Marqueurs tumoraux', 'mUI/mL', '<5 (H), <5 (F non enceinte)', NOW(), NOW()),
    ('NSE (Enolase Neuro-Spécifique)', 'Marqueurs tumoraux', 'ng/mL', '<16.3', NOW(), NOW()),
    ('CYFRA 21-1', 'Marqueurs tumoraux', 'ng/mL', '<3.3', NOW(), NOW()),
    ('S100', 'Marqueurs tumoraux', 'μg/L', '<0.12', NOW(), NOW()),
    ('Chromogranine A', 'Marqueurs tumoraux', 'μg/L', '<100', NOW(), NOW()),
    
    -- 5. Infectiologie
    ('Sérologie VIH', 'Infectiologie', NULL, 'Négatif', NOW(), NOW()),
    ('Ag HBs (Hépatite B)', 'Infectiologie', NULL, 'Négatif', NOW(), NOW()),
    ('Ac anti-HBc', 'Infectiologie', NULL, NULL, NOW(), NOW()),
    ('Ac anti-HBs', 'Infectiologie', NULL, NULL, NOW(), NOW()),
    ('Ac anti-VHC (Hépatite C)', 'Infectiologie', NULL, 'Négatif', NOW(), NOW()),
    ('VDRL/RPR (Syphilis)', 'Infectiologie', NULL, 'Négatif', NOW(), NOW()),
    ('TPHA (Syphilis)', 'Infectiologie', NULL, 'Négatif', NOW(), NOW()),
    ('Ac anti-Chlamydia', 'Infectiologie', NULL, NULL, NOW(), NOW()),
    ('Ac anti-Mycoplasma', 'Infectiologie', NULL, NULL, NOW(), NOW()),
    ('Ac anti-Toxoplasma (IgG et IgM)', 'Infectiologie', NULL, NULL, NOW(), NOW()),
    ('Ac anti-Rubéole (IgG et IgM)', 'Infectiologie', NULL, NULL, NOW(), NOW()),
    ('Ac anti-CMV (IgG et IgM)', 'Infectiologie', NULL, NULL, NOW(), NOW()),
    ('Ac anti-EBV (EBNA, VCA)', 'Infectiologie', NULL, NULL, NOW(), NOW()),
    ('Ac anti-Herpès (HSV1 et HSV2)', 'Infectiologie', NULL, NULL, NOW(), NOW()),
    ('Ac anti-Varicelle-Zona (VZV)', 'Infectiologie', NULL, NULL, NOW(), NOW()),
    ('Ac anti-Parvovirus B19', 'Infectiologie', NULL, NULL, NOW(), NOW()),
    ('Hélicobacter pylori (sérologie)', 'Infectiologie', NULL, NULL, NOW(), NOW()),
    ('Test respiratoire à l''urée (Hélicobacter)', 'Infectiologie', NULL, NULL, NOW(), NOW()),
    ('Antistreptolysines O (ASLO)', 'Infectiologie', 'UI/mL', '<200', NOW(), NOW()),
    ('Procalcitonine', 'Infectiologie', 'ng/mL', '<0.5', NOW(), NOW()),
    
    -- 6. Urine
    ('Analyse d''urine complète', 'Urine', NULL, NULL, NOW(), NOW()),
    ('ECBU (Examen Cyto-Bactériologique des Urines)', 'Urine', NULL, NULL, NOW(), NOW()),
    ('Protéinurie des 24h', 'Urine', 'mg/24h', '<150', NOW(), NOW()),
    ('Microalbuminurie', 'Urine', 'mg/24h', '<30', NOW(), NOW()),
    ('Rapport albumine/créatinine urinaire', 'Urine', 'mg/g', '<30', NOW(), NOW()),
    ('Créatininurie', 'Urine', 'mg/24h', 'Varie selon masse musculaire', NOW(), NOW()),
    ('Clairance de la créatinine', 'Urine', 'mL/min', '90-140 (H), 80-125 (F)', NOW(), NOW()),
    ('Glycosurie', 'Urine', NULL, 'Négatif', NOW(), NOW()),
    ('Corps cétoniques urinaires', 'Urine', NULL, 'Négatif', NOW(), NOW()),
    ('Uricurie', 'Urine', 'mg/24h', '250-750', NOW(), NOW()),
    ('Calciurie', 'Urine', 'mg/24h', '100-300', NOW(), NOW()),
    ('Phosphaturie', 'Urine', 'mg/24h', '400-1300', NOW(), NOW()),
    ('Oxalurie', 'Urine', 'mg/24h', '<45', NOW(), NOW()),
    ('Cystinurie', 'Urine', 'mg/24h', '<30', NOW(), NOW()),
    ('Sodium urinaire', 'Urine', 'mEq/24h', '40-220', NOW(), NOW()),
    ('Potassium urinaire', 'Urine', 'mEq/24h', '25-125', NOW(), NOW()),
    ('Chlore urinaire', 'Urine', 'mEq/24h', '110-250', NOW(), NOW()),
    ('Osmolalité urinaire', 'Urine', 'mOsm/kg', '50-1200', NOW(), NOW()),
    ('Densité urinaire', 'Urine', NULL, '1.002-1.030', NOW(), NOW()),
    ('pH urinaire', 'Urine', NULL, '4.5-8.0', NOW(), NOW()),
    
    -- 7. Coagulation
    ('Temps de Prothrombine (TP)', 'Coagulation', 'sec', '11-13.5', NOW(), NOW()),
    ('INR', 'Coagulation', NULL, '0.8-1.2', NOW(), NOW()),
    ('Temps de Céphaline Activé (TCA)', 'Coagulation', 'sec', '25-35', NOW(), NOW()),
    ('Temps de Thrombine (TT)', 'Coagulation', 'sec', '14-19', NOW(), NOW()),
    ('Fibrinogène', 'Coagulation', 'g/L', '2.0-4.0', NOW(), NOW()),
    ('D-Dimères', 'Coagulation', 'ng/mL', '<500', NOW(), NOW()),
    ('Antithrombine III', 'Coagulation', '%', '80-120', NOW(), NOW()),
    ('Protéine C', 'Coagulation', '%', '70-140', NOW(), NOW()),
    ('Protéine S', 'Coagulation', '%', '60-150', NOW(), NOW()),
    ('Facteur II', 'Coagulation', '%', '70-120', NOW(), NOW()),
    ('Facteur V', 'Coagulation', '%', '70-120', NOW(), NOW()),
    ('Facteur VII', 'Coagulation', '%', '70-120', NOW(), NOW()),
    ('Facteur VIII', 'Coagulation', '%', '50-150', NOW(), NOW()),
    ('Facteur IX', 'Coagulation', '%', '70-120', NOW(), NOW()),
    ('Facteur X', 'Coagulation', '%', '70-120', NOW(), NOW()),
    ('Facteur XI', 'Coagulation', '%', '70-120', NOW(), NOW()),
    ('Facteur XII', 'Coagulation', '%', '70-120', NOW(), NOW()),
    ('Facteur XIII', 'Coagulation', '%', '70-120', NOW(), NOW()),
    ('Temps de saignement', 'Coagulation', 'min', '2-8', NOW(), NOW()),
    ('Temps de coagulation', 'Coagulation', 'min', '5-10', NOW(), NOW()),
    
    -- 8. Immunologie
    ('Facteur rhumatoïde', 'Immunologie', 'UI/mL', '<20', NOW(), NOW()),
    ('Anti-CCP', 'Immunologie', 'U/mL', '<20', NOW(), NOW()),
    ('ANCA (Anti-Cytoplasme des Neutrophiles)', 'Immunologie', NULL, 'Négatif', NOW(), NOW()),
    ('Anti-ADN natif', 'Immunologie', 'UI/mL', '<30', NOW(), NOW()),
    ('Anti-nucléaires (FAN)', 'Immunologie', NULL, 'Négatif (<1/80)', NOW(), NOW()),
    ('Anti-ENA (Extractable Nuclear Antigen)', 'Immunologie', NULL, 'Négatif', NOW(), NOW()),
    ('Anti-Sm', 'Immunologie', NULL, 'Négatif', NOW(), NOW()),
    ('Anti-RNP', 'Immunologie', NULL, 'Négatif', NOW(), NOW()),
    ('Anti-SSA (Ro)', 'Immunologie', NULL, 'Négatif', NOW(), NOW()),
    ('Anti-SSB (La)', 'Immunologie', NULL, 'Négatif', NOW(), NOW()),
    ('Anti-Scl70', 'Immunologie', NULL, 'Négatif', NOW(), NOW()),
    ('Anti-Jo1', 'Immunologie', NULL, 'Négatif', NOW(), NOW()),
    ('Anti-cardiolipines (IgG et IgM)', 'Immunologie', 'U/mL', '<20', NOW(), NOW()),
    ('Anti-bêta2 glycoprotéine I', 'Immunologie', 'U/mL', '<20', NOW(), NOW()),
    ('Lupus anticoagulant', 'Immunologie', NULL, 'Négatif', NOW(), NOW()),
    ('Complément C3', 'Immunologie', 'mg/dL', '90-180', NOW(), NOW()),
    ('Complément C4', 'Immunologie', 'mg/dL', '10-40', NOW(), NOW()),
    ('CH50', 'Immunologie', 'U/mL', '30-75', NOW(), NOW()),
    ('IgE totales', 'Immunologie', 'UI/mL', '<150', NOW(), NOW()),
    ('IgG', 'Immunologie', 'mg/dL', '700-1600', NOW(), NOW()),
    ('IgA', 'Immunologie', 'mg/dL', '70-400', NOW(), NOW()),
    ('IgM', 'Immunologie', 'mg/dL', '40-230', NOW(), NOW()),
    ('IgD', 'Immunologie', 'mg/dL', '<14', NOW(), NOW()),
    ('Phadiatop', 'Immunologie', NULL, 'Négatif', NOW(), NOW()),
    ('RAST (Allergènes spécifiques)', 'Immunologie', 'UI/mL', '<0.35', NOW(), NOW()),
    
    -- 9. Génétique
    ('Caryotype', 'Génétique', NULL, NULL, NOW(), NOW()),
    ('PCR spécifique', 'Génétique', NULL, NULL, NOW(), NOW()),
    ('Séquençage génétique', 'Génétique', NULL, NULL, NOW(), NOW()),
    ('Test de paternité', 'Génétique', NULL, NULL, NOW(), NOW()),
    
    -- 10. Toxicologie
    ('Dépistage toxicologique urinaire', 'Toxicologie', NULL, 'Négatif', NOW(), NOW()),
    ('Alcoolémie', 'Toxicologie', 'g/L', '<0.5', NOW(), NOW()),
    ('Dosage de médicaments', 'Toxicologie', NULL, NULL, NOW(), NOW()),
    ('Métaux lourds (Plomb, Mercure, etc.)', 'Toxicologie', NULL, NULL, NOW(), NOW())
    
   