export enum HistoryType {
  ALLERGY = 'ALLERGY',
  CHRONIC_DISEASE = 'CHRONIC_DISEASE',
  SURGERY = 'SURGERY',
  HOSPITALIZATION = 'HOSPITALIZATION',
  FAMILY_HISTORY = 'FAMILY_HISTORY',
  VACCINATION = 'VACCINATION',
  OTHER = 'OTHER'
}
